version: '3'

services:
  wi-room-release:
    image: jeremywillans/wi-room-release:latest
    container_name: wi-room-release
    env_file:
      - .env
    volumes:
      - room-release-config:/config
    restart: unless-stopped
    networks:
      - internal

volumes:
  room-release-config:

networks:
  internal:
